### ISSUE TITLE
Characters saved as HTML Entities

### ISSUE THREAD

**Issue by kiger** [anomalylabs/translator-module#5]
If I translate the Save & Exit string as Save & Exit the updated string was Save &amp; Exit. After that everywhere in the system the button is Save &amp; Exit.
![pyrohiba](https://cloud.githubusercontent.com/assets/2277562/16568508/55d0ec9c-422b-11e6-8e90-a88cc06cb2f3.png)

**Comment by RyanThompson** [comment]
Should be fixed with this: https://github.com/anomalylabs/streams-platform/commit/336bd43e09bb05026d6583a87b5926f6e457a0d5 <https://github.com/anomalylabs/streams-platform/commit/336bd43e09bb05026d6583a87b5926f6e457a0d5>

From now on please put issues in the main pyrocms/pyrocms repository and just prefix with [translator-module] or something. Thanks!
